VESSELS = [
  "SAMUDRA SARVEKSHAK",
  "Sea Jaguar",
  "Sea Conquest",
  "KM 180",
  "AQUA FLOAT",
  "DLB KANENNA",
  "SUMAYLA ONE",
  "MAHI",
  "FUGRO MAPPER",
  "KIRANJOG",
  "AQUATOR-2",
  "RESILIANT",
  "URJA",
  "SHAKTI",
  "NAND SAARTHI",
  "IVY",
  "DHP SHIVALIK",
  "CHANDRA PLUTO",
  "VISTA 9",
  "SEAMEC-III",
  "ZD LIBRA",
  "VALLIANZ PRELUDE",
  "ZD AQUARIOUS",
  "RAWABI OPAL",
  "MARI GOLD",
  "SHIVANSH SHAMBHAVI",
  "SHIVALI II",
  "GSP BIGFOOT 1",
  "HEERA",
  "IRON TUG",
  "ENA CHALLENGER",
  "ALBETROSS 37",
  "PARVATI",
  "SHIVALI",
  "AVTAR VICTORY",
  "HAI LONG 106",
  "TRITON ENERGY",
  "MP PROWESS",
  "BES POWER",
  "ANUSUIYA",
  "AVTAR COURAGE",
  "FAIRMACS",
  "DRA I",
  "SAGA",
  "ACOMS 11",
  "SHIVAM",
  "SHIVANSH PRIYA",
  "Vanessa-7",
  "Vanessa-6",
  "Shivansh Aryan",
  "EXL 1",
  "VMS 6",
  "SeaQuest Garuda",
  "AJR WB 1",
  "Gomti",
  "Meenakshi",
  "Seamec Princess",
  "AF 250",
  "RMG 254",
  "Vishvanetra",
  "Sagar-5",
  "AB 3000",
  "Heera-1",
  "Sangita",
  "Victoria 250",
  "Posh Panglima",
  "Posh Arcturus",
  "JT Odyssey",
  "Creative-1",
  "Varshne",
  "Kenwell 93",
  "Sumain Tangkas",
  "VMS 3",
  "VMS 21",
  "MICLYN CONSTRUCTOR I",
  "Offshore Ranger",
  "Britoil 81",
  "Britoil 71",
  "Malaviya Sixteen",
  "Posh Natuna",
  "OCEAN DIAMOND",
  "EMERALD",
  "ALAACRITY 666",
  "Offshore Supporter",
  "Two Nadim",
  "Seamec Glorious",
  "Saksham",
  "Orion Laxmi",
  "VIKING SPIRIT",
  "AQUA TOW",
  "Triton vision",
  "AK Ship 1",
  "LTS-3000",
  "Two Aryan",
  "Megallan 2",
  "Shree Varsha",
  "Towing Tug 5",
  "Sharief Reliance",
  "Sharief Falcon",
  "VALLIANZ AQUARIUS",
  "DRA 1",
  "VICTORIA 251",
  "SHIVALI 2",
  "SEA Venture",
]
